detectors:
  ControlParameter:
    exclude:
      - Vajra::CLI::Launcher#app
  UncommunicativeVariableName:
    accept:
      - e
      - _
  TooManyStatements:
    enabled: true
    max_statements: 25
  TooManyConstants:
    enabled: true
    max_constants: 10
  UtilityFunction:
    enabled: false
  NilCheck:
    enabled: true
    exclude:
      - Vajra::CLI::Launcher#normalize_setting_values
      - Vajra::Internal::Tracing#with_request_span
exclude_paths:
  - performance/**/*
  - spec/**/*
  - bin/*
  - tmp/**/*
