# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source "https://rubygems.org"

gemspec

gem "irb"
gem "rake", "~> 13.0"
gem "rake-compiler"
gem "rbs"
gem "reek", "~> 6.5"
gem "simplecov", "~> 0.22", require: false

group :development do
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.85"
  gem "rubocop-rake"
  gem "rubocop-rspec"
  gem "ruby-lsp", require: false
  gem "ruby-lsp-rails", require: false
  gem "ruby-lsp-rspec", require: false
end
