# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

require 'bundler/gem_tasks'
require 'rake/extensiontask'

GEMSPEC = Gem::Specification.load('vajra.gemspec')

Rake::ExtensionTask.new('vajra', GEMSPEC) do |ext|
  ext.ext_dir = 'ext/vajra'
  ext.lib_dir = 'lib/vajra'
end

task default: :compile
