# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

valid_prefixes = %w[feat/ bugfix/ docs/ release/ chore/ refactor/ test/ style/ ci/ perf/ build/]

def all_modified_files(git)
  all_added = git.added_files + git.modified_files + git.renamed_files.map { |file| file[:after] }
  all_removed = git.deleted_files + git.renamed_files.map { |file| file[:before] }
  (all_added - all_removed).uniq
end

modified_files = all_modified_files(git)

fail("Please include a more detailed description of your change.") if github.pr_body.strip.length < 10

if github.branch_for_head && valid_prefixes.none? { |prefix| github.branch_for_head.start_with?(prefix) }
  fail("PR branch name should start with one of: #{valid_prefixes.join(', ')}")
end

if github.pr_title && valid_prefixes.none? { |prefix| github.pr_title.start_with?("#{prefix.delete_suffix('/')}:") }
  fail("PR title should start with one of: #{valid_prefixes.map { |p| "#{p.delete_suffix('/')}:" }.join(', ')}")
end

if modified_files.include?("gems/vajra/Gemfile") && !modified_files.include?("gems/vajra/Gemfile.lock")
  fail("Gemfile changed but Gemfile.lock did not. Did you forget to run bundle install?")
end

modified_files.each do |file|
  diff = git.diff_for_file(file)
  debug_statement_patterns = [/\bbinding\.(?:pry|b)\b/, /\bbyebug\b/, /\bdebugger\b/]
  if file.end_with?(".rb") && diff && debug_statement_patterns.any? { |pattern| diff.patch.match?(pattern) }
    fail("Do not commit debugging statements. Found in #{file}")
  end
end
