# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Vajra
  module CLI
    class Error < Vajra::Error
    end

    def self.start!: (?argv: Array[String], ?root: String, ?stdout: IO) -> nil
  end
end
