# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64'
gem 'falcon'
gem 'fiddle'
gem 'hanami'
gem 'hanami-controller'
gem 'hanami-router'
gem 'json', '>= 2.21.2'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-sdk'
gem 'passenger'
gem 'puma'
gem 'rack'
gem 'rackup'
gem 'rails', '>= 8.1.3.1', '< 8.2'
gem 'rake', require: false
gem 'roda'
gem 'sinatra'
gem 'vajra', path: '..'
