# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Vajra
  VERSION: String

  def self.header: () -> String
  def self.start: () -> nil
  def self.stop: () -> nil
end
