# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Vajra
  class Error < StandardError
  end

  VERSION: String

  def self.header: () -> String
  def self.install_optional_railtie: () -> bool?
  def self.configure: [T, R] () { (T) -> R } -> R
                     | [T, R] () { (?T) -> R } -> R
                     | [T, R] () { (*T) -> R } -> R
                     | [R] () { () -> R } -> R
  def self.start: (
    ?host: String,
    ?port: Integer,
    ?workers: Integer,
    ?threads: [Integer] | [Integer, Integer],
    ?max_connections: Integer,
    ?queue_capacity: Integer,
    ?scheduler_policy: String,
    ?max_request_head_bytes: Integer,
    ?request_timeout: Integer,
    ?first_data_timeout: Integer,
    ?persistent_timeout: Integer,
    ?worker_timeout: Integer,
    ?request_head_timeout: Integer,
    ?log_level: String
  ) -> nil
  def self.stop: () -> nil
end
