#!/bin/sh
# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "${SCRIPT_DIR}/run-common"
BUNDLE_PATH="${BUNDLE_PATH:-${REPO_ROOT}/vendor/bundle}"

export BUNDLE_PATH

install_bundle_if_present() {
  suite_dir="$1"

  [ -f "${REPO_ROOT}/${suite_dir}/Gemfile" ] || return 0

  cd "${REPO_ROOT}/${suite_dir}"
  ruby -S bundle check || ruby -S bundle install
}

install_bundle_if_present "gems/vajra"
install_bundle_if_present "docs"
