#!/bin/sh
# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "${SCRIPT_DIR}/run-common"

run_cmd "docs-build" sh -c "cd \"${REPO_ROOT}/docs\" && bundle exec jekyll build"
