# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
source "https://rubygems.org"

gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "just-the-docs", git: "https://github.com/niteshpurohit/just-the-docs.git", ref: "933dc227584741c30a343cec25a1f315a3153988"
  gem "github-pages", "~> 232"
  gem "kramdown"
end

platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:windows]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
